### PR TITLE
Makes the dealer not waste time on using meaningless items.

### LINKED ISSUE #16: The evil dealer threw the inverter away for nothing
I didn't have too much luck in this game, so I unfortunately lost the battle

Dealer was so angry that he threatened me with death exactly three times, he succeeded, but for some reason only on the third (The phrases appeared for some unknown reason, because Diller couldn't kill me at those moments).

Then he got so angry that he just threw the adrenaline off the table, apparently he really wanted to win (It's important to mention that by that time I had exactly zero items).

Still, he managed to kill me, but there were two small, though not critical, bugs. I hope this helps in some way

https://github.com/ITR13/BuckshotRouletteMods/assets/72986030/3142600c-38fd-43a2-9fbb-bb3826793059

### PR DESCRIPTION
**Pull request by ballardrog**
Adds `depth` to `Result` as discussed in https://github.com/ITR13/BuckshotRouletteMods/pull/13#issuecomment-2156650731. (Fixes #16.)

### CODE REVIEW

**Comment by Voenkomat1488** [comment]
Thanks! Maybe it's a minor bug, but nevertheless Dealer will become at least a little smarter)

**Comment by ITR13** [comment]
Will have to check if it causes the dealer to off themselves quicker if they're about to die, might need an inverse depth check when DeathChance of current is bigger than DeathChance of opponent, I'll do some testing later!

**Comment by ballardrog** [comment]
It does cause the dealer to shoot himself if he knows he's guaranteed to die, but in my experience it's pretty rare for him to be both holding the gun and guaranteed to die. I don't know if him spending time wasting everything is really better in that situation, though.

**Comment by MSLaFaver** [comment]
> I don't know if him spending time wasting everything is really better in that situation, though.

Wouldn't keeping his items and killing himself be better for the carryover round? In that case, maybe have him waste just a few items to make space for new ones?

**Comment by ballardrog** [comment]
In the carryover round he still tries to set himself up for the next round. It's only in the non-carryover rounds that everything gets zeroed out.

**Comment by MSLaFaver** [comment]
(By the way @ballardrog I'm looking into implementing this for a server and I'd love some feedback. My Discord username is mslafaver if you want to reach out, GitHub doesn't have a good messaging system.)

**Comment by ITR13** [comment]
Sounds good, I'll try to make a new release tomorrow 
EDIT: I forgot

**Pull request merged**
